import { createHash } from "node:crypto";
import { getRedis } from "../store/redis.ts";
import type { RecoveryMandateAuthorityBoundaryStore as Store } from "../ledger/recovery-mandate-authority-boundary.ts";
import { recoveryMandateAuthorityVersionKey } from "../ledger/recovery-mandate-authority-boundary.ts";
import { recoveryOperationKey } from "../ledger/recovery-mandate-operation.ts";
import { currentMandateKey } from "../ledger/recovery-mandate-current.ts";
import { readRetainedRecoveryOutput, retainedRecoveryOutputKey } from "../ledger/recovery-retained-output.ts";
import { loadCurrentPaymentRecord, currentPaymentRecordKey } from "../hedera-agent-kit/current-payment-record.ts";
import { currentBusinessEligibilityKey } from "../hedera-agent-kit/current-business-eligibility.ts";
import { publishedProviderPolicyKey } from "../policy/published-provider-policy.ts";
import { validateExternallySignedRecovery, type ExternalRecoveryLifecycleDependencies } from "../recovery/external-recovery-lifecycle.ts";

export type AuthenticatedHumanSubmissionAuthorization={schemaVersion:1;kind:"YOURTURN_HEDERA_TESTNET_ONE_SHOT_AUTHORIZATION";network:"testnet";oneShot:true;authenticated:true;authorizationId:string;ownerId:string;operationId:string;intentHash:string;transactionId:string;transactionBytesSha256:string;authorizedAtMs:number;expiresAtMs:number;};
export type OneShotSubmissionRecord={schemaVersion:1;network:"testnet";ownerId:string;operationId:string;intentHash:string;transactionId:string;transactionBytesSha256:string;humanAuthorizationDigest:string;claimedAtMs:number;updatedAtMs:number;state:"dispatch-claimed"|"dispatch-accepted"|"dispatch-unknown";};
export type OneShotSubmitterDependencies={
  store?:Store;network:"testnet";resolveCurrentSigningState:ExternalRecoveryLifecycleDependencies["resolveCurrentSigningState"];
  /** Trusted server/human-ceremony boundary: authenticate the human and atomically consume this one-shot authorization outside request JSON. */
  consumeAuthenticatedHumanAuthorization(request:Readonly<{schemaVersion:1;kind:"YOURTURN_HEDERA_TESTNET_ONE_SHOT_REQUEST";network:"testnet";ownerId:string;operationId:string;intentHash:string;transactionId:string;transactionBytesSha256:string;observedAtMs:number;validUntilMs:number;}>):Promise<AuthenticatedHumanSubmissionAuthorization|null>;
  /** Trusted TESTNET transport only: dispatch these exact already-signed bytes without signing/freezing/rebuilding/retrying. */
  dispatchExactTestnet(request:Readonly<{network:"testnet";operationId:string;transactionId:string;transactionBytesBase64:string;transactionBytesSha256:string;humanAuthorizationDigest:string;}>):Promise<{outcome:"accepted"|"unknown";transactionId:string}>;
  now?:()=>number;
};
export class OneShotSubmissionDenied extends Error{constructor(readonly code:string){super(code);this.name="OneShotSubmissionDenied";}}
function requireSubmit(ok:unknown,code:string):asserts ok{if(!ok)throw new OneShotSubmissionDenied(code);}
const label=(v:unknown):v is string=>typeof v==="string"&&/^[A-Za-z0-9._:@-]{1,200}$/.test(v),opid=(v:unknown):v is string=>typeof v==="string"&&/^[A-Za-z0-9._:-]{1,128}$/.test(v),digest=(v:unknown):v is string=>typeof v==="string"&&/^[a-f0-9]{64}$/.test(v),txid=(v:unknown):v is string=>typeof v==="string"&&/^0\.0\.[1-9][0-9]{0,18}@[1-9][0-9]{0,18}\.[0-9]{9}$/.test(v),safeMs=(v:unknown):v is number=>Number.isSafeInteger(v)&&(v as number)>=0;
const recordFields="claimedAtMs,humanAuthorizationDigest,intentHash,network,operationId,ownerId,schemaVersion,state,transactionBytesSha256,transactionId,updatedAtMs",authorizationFields="authenticated,authorizationId,authorizedAtMs,expiresAtMs,intentHash,kind,network,oneShot,operationId,ownerId,schemaVersion,transactionBytesSha256,transactionId";
function exactBytes(input:unknown){requireSubmit(typeof input==="string"&&input.length>0&&input.length<=87384&&/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(input),"SIGNED_TRANSACTION_BYTES_INVALID");const bytes=Buffer.from(input,"base64");requireSubmit(bytes.length>0&&bytes.length<=65536&&bytes.toString("base64")===input,"SIGNED_TRANSACTION_BYTES_INVALID");return {bytesBase64:input,sha256:createHash("sha256").update(bytes).digest("hex")};}
function exactSelection(input:unknown){requireSubmit(!!input&&typeof input==="object"&&!Array.isArray(input),"SUBMISSION_SELECTION_REQUIRED");const r=input as Record<string,unknown>;requireSubmit(Object.keys(r).sort().join(",")==="intentHash,operationId,ownerId,signedTransactionBytesBase64","SUBMISSION_SELECTION_FIELDS_INVALID");requireSubmit(label(r.ownerId)&&opid(r.operationId)&&digest(r.intentHash),"SUBMISSION_SELECTION_INVALID");return Object.freeze({ownerId:r.ownerId,operationId:r.operationId,intentHash:r.intentHash,...exactBytes(r.signedTransactionBytesBase64)});}
function parseAuthorization(raw:unknown,s:ReturnType<typeof exactSelection>,transactionId:string,nowMs:number){requireSubmit(!!raw&&typeof raw==="object"&&!Array.isArray(raw)&&Object.keys(raw).sort().join(",")===authorizationFields,"HUMAN_SUBMISSION_AUTHORIZATION_REQUIRED");const a=structuredClone(raw) as AuthenticatedHumanSubmissionAuthorization;requireSubmit(a.schemaVersion===1&&a.kind==="YOURTURN_HEDERA_TESTNET_ONE_SHOT_AUTHORIZATION"&&a.network==="testnet"&&a.oneShot===true&&a.authenticated===true&&label(a.authorizationId)&&a.ownerId===s.ownerId&&a.operationId===s.operationId&&a.intentHash===s.intentHash&&a.transactionId===transactionId&&a.transactionBytesSha256===s.sha256&&safeMs(a.authorizedAtMs)&&safeMs(a.expiresAtMs)&&a.authorizedAtMs<=nowMs&&nowMs<a.expiresAtMs&&a.expiresAtMs>a.authorizedAtMs&&a.expiresAtMs-a.authorizedAtMs<=60_000&&nowMs-a.authorizedAtMs<=60_000,"HUMAN_SUBMISSION_AUTHORIZATION_REQUIRED");return Object.freeze(a);}
export function authenticatedHumanAuthorizationDigest(raw:AuthenticatedHumanSubmissionAuthorization){const a=structuredClone(raw);requireSubmit(a&&typeof a==="object"&&Object.keys(a).sort().join(",")===authorizationFields,"HUMAN_SUBMISSION_AUTHORIZATION_REQUIRED");return createHash("sha256").update(JSON.stringify(Object.fromEntries(authorizationFields.split(",").map(k=>[k,a[k as keyof AuthenticatedHumanSubmissionAuthorization]])))).digest("hex");}
function encodeRecord(r:OneShotSubmissionRecord){return JSON.stringify(Object.fromEntries(recordFields.split(",").map(k=>[k,r[k as keyof OneShotSubmissionRecord]])));}
function parseRecord(raw:unknown):OneShotSubmissionRecord{let r:any;try{r=typeof raw==="string"?JSON.parse(raw):structuredClone(raw);}catch{throw new OneShotSubmissionDenied("SUBMISSION_RECORD_MALFORMED");}requireSubmit(r&&typeof r==="object"&&!Array.isArray(r)&&Object.keys(r).sort().join(",")===recordFields&&r.schemaVersion===1&&r.network==="testnet"&&label(r.ownerId)&&opid(r.operationId)&&digest(r.intentHash)&&txid(r.transactionId)&&digest(r.transactionBytesSha256)&&digest(r.humanAuthorizationDigest)&&safeMs(r.claimedAtMs)&&safeMs(r.updatedAtMs)&&r.claimedAtMs<=r.updatedAtMs&&["dispatch-claimed","dispatch-accepted","dispatch-unknown"].includes(r.state),"SUBMISSION_RECORD_MALFORMED");return Object.freeze(r as OneShotSubmissionRecord);}
export function oneShotSubmissionKey(operationId:string){requireSubmit(opid(operationId),"INVALID_OPERATION_ID");return `bookedrights:hedera:one-shot-submit:${operationId}`;}
export async function readOneShotSubmissionRecord(store:Pick<Store,"get">,operationId:string){const raw=await store.get(oneShotSubmissionKey(operationId));return raw===null?null:parseRecord(raw);}

export const ONE_SHOT_SUBMISSION_CLAIM_LUA=`
-- YOURTURN_ONE_SHOT_CLAIM_V3
if redis.call("EXISTS",KEYS[1])~=0 then return 0 end
local t=redis.call("TIME")
local nowms=tonumber(t[1])*1000+math.floor(tonumber(t[2])/1000)
if not nowms or nowms>=tonumber(ARGV[2]) or nowms>=tonumber(ARGV[3]) then return -2 end
if #KEYS~=8 or #ARGV~=10 then return -4 end
for i=2,8 do
  if (redis.call("GET",KEYS[i]) or "")~=ARGV[i+2] then return -3 end
end
redis.call("SET",KEYS[1],ARGV[1])
return 1
`;
export const ONE_SHOT_SUBMISSION_FINALIZE_LUA=`
-- YOURTURN_ONE_SHOT_FINALIZE_V3
if (redis.call("GET",KEYS[1]) or "")~=ARGV[1] then return -1 end
redis.call("SET",KEYS[1],ARGV[2])
return 1
`;
async function exactStartedContext(store:Store,s:ReturnType<typeof exactSelection>){const retained=await readRetainedRecoveryOutput({store,ownerId:s.ownerId,operationId:s.operationId,intentHash:s.intentHash});requireSubmit(retained!==null&&retained.operation.phase==="effect-started","STARTED_RETAINED_OPERATION_REQUIRED");requireSubmit(txid(retained.operation.transactionId)&&retained.operation.transactionId===retained.record.transactionId&&retained.operation.envelopeDigest===retained.record.envelopeDigest,"RETAINED_OPERATION_REFERENCES_REQUIRED");return retained;}
function assertSameSubmission(record:OneShotSubmissionRecord,s:ReturnType<typeof exactSelection>,transactionId:string){requireSubmit(record.network==="testnet"&&record.ownerId===s.ownerId&&record.operationId===s.operationId&&record.intentHash===s.intentHash&&record.transactionId===transactionId&&record.transactionBytesSha256===s.sha256,"SUBMISSION_RECORD_CONFLICT");}
function resultFromRecord(record:OneShotSubmissionRecord,alreadyRecorded:boolean,storageFinalized=true){return Object.freeze({kind:"HEDERA_TESTNET_ONE_SHOT_SUBMISSION" as const,status:record.state==="dispatch-accepted"?"ACCEPTED_RECONCILIATION_REQUIRED" as const:"OUTCOME_UNKNOWN_RECONCILIATION_REQUIRED" as const,record,alreadyRecorded,networkDispatchAttempted:!alreadyRecorded,storageFinalized,reconciliationRequired:true as const,consensusProven:false as const,completionPermit:false as const,executionPermit:false as const});}
async function redisSubmissionFence(store:Store,s:ReturnType<typeof exactSelection>,initial:Awaited<ReturnType<typeof exactStartedContext>>,now:()=>number){
  const payment=await loadCurrentPaymentRecord({store,now,operationId:s.operationId,authenticatedOwnerId:s.ownerId});requireSubmit(payment.commitment.transactionId===initial.record.transactionId&&payment.commitment.bookingTokenId===initial.operation.token&&String(payment.commitment.serial)===initial.operation.serial,"SUBMISSION_PAYMENT_SCOPE_CHANGED");
  const serial=Number(initial.operation.serial);requireSubmit(Number.isSafeInteger(serial)&&serial>0,"SUBMISSION_SERIAL_INVALID");
  const guardKeys=[recoveryMandateAuthorityVersionKey(BigInt(serial)),recoveryOperationKey(s.operationId),currentMandateKey(initial.operation.token,BigInt(serial)),retainedRecoveryOutputKey(s.operationId),currentPaymentRecordKey(s.operationId),currentBusinessEligibilityKey(s.operationId),publishedProviderPolicyKey({providerId:payment.providerId,tokenId:initial.operation.token,serial})];
  const raw=await Promise.all(guardKeys.map(k=>store.get(k)));requireSubmit(raw[0]!==null&&String(raw[0])===String(initial.operation.ownedVersion)&&raw.slice(1).every(v=>typeof v==="string"&&v.length>0),"SUBMISSION_FENCE_STATE_UNAVAILABLE");
  return Object.freeze({keys:guardKeys,values:[String(raw[0]),...(raw.slice(1) as string[])]});
}

/** Canonical fail-closed control for one externally signed TESTNET dispatch. The existing BEFORE_SUBMIT validator is not injectable here. A permanent Redis claim is atomically fenced against the operation-owned authority version and exact operation/pointer/retained-output/payment/eligibility/provider-policy records immediately before the only transport call. */
export async function submitExternalRecoveryOnce(input:{ownerId:string;operationId:string;intentHash:string;signedTransactionBytesBase64:string},dependencies:OneShotSubmitterDependencies){
  requireSubmit(dependencies?.network==="testnet"&&typeof dependencies.resolveCurrentSigningState==="function"&&typeof dependencies.consumeAuthenticatedHumanAuthorization==="function"&&typeof dependencies.dispatchExactTestnet==="function","TESTNET_SUBMISSION_DEPENDENCIES_REQUIRED");
  const s=exactSelection(input),store=dependencies.store??getRedis(),now=dependencies.now??Date.now;let lastNow=now();requireSubmit(safeMs(lastNow),"SUBMISSION_CLOCK_INVALID");const tick=()=>{const n=now();requireSubmit(safeMs(n)&&n>=lastNow,"SUBMISSION_CLOCK_INVALID");lastNow=n;return n;};
  const initial=await exactStartedContext(store,s),transactionId=initial.record.transactionId;const existing=await readOneShotSubmissionRecord(store,s.operationId);if(existing){assertSameSubmission(existing,s,transactionId);return resultFromRecord(existing,true);}
  const validateNow=async()=>{const r=await validateExternallySignedRecovery({ownerId:s.ownerId,operationId:s.operationId,intentHash:s.intentHash,signedTransactionBytesBase64:s.bytesBase64},{store,resolveCurrentSigningState:dependencies.resolveCurrentSigningState,now});requireSubmit(r.ok&&r.phase==="BEFORE_SUBMIT"&&r.operationId===s.operationId&&r.transactionId===transactionId&&r.transactionBytesBase64===s.bytesBase64&&r.transactionBytesSha256===s.sha256&&r.executionPermit===false&&r.submitted===false&&r.signedByThisModule===false&&safeMs(r.observedAtMs)&&safeMs(r.validUntilMs)&&r.observedAtMs<r.validUntilMs,"BEFORE_SUBMIT_VALIDATION_REQUIRED");return r;};
  const preview=await validateNow();const authRequest=Object.freeze({schemaVersion:1 as const,kind:"YOURTURN_HEDERA_TESTNET_ONE_SHOT_REQUEST" as const,network:"testnet" as const,ownerId:s.ownerId,operationId:s.operationId,intentHash:s.intentHash,transactionId,transactionBytesSha256:s.sha256,observedAtMs:preview.observedAtMs,validUntilMs:preview.validUntilMs});
  const authorization=parseAuthorization(await dependencies.consumeAuthenticatedHumanAuthorization(authRequest),s,transactionId,tick()),humanAuthorizationDigest=authenticatedHumanAuthorizationDigest(authorization);
  const fence=await redisSubmissionFence(store,s,initial,now);const finalValidation=await validateNow();requireSubmit(finalValidation.transactionId===preview.transactionId&&finalValidation.transactionBytesBase64===s.bytesBase64&&finalValidation.transactionBytesSha256===preview.transactionBytesSha256&&finalValidation.observedAtMs>=preview.observedAtMs,"SUBMISSION_VALIDATION_CHANGED");
  const claimTime=tick();requireSubmit(claimTime<finalValidation.validUntilMs&&claimTime<authorization.expiresAtMs,"SUBMISSION_AUTHORIZATION_OR_VALIDATION_EXPIRED");const claimed:OneShotSubmissionRecord=Object.freeze({schemaVersion:1,network:"testnet",ownerId:s.ownerId,operationId:s.operationId,intentHash:s.intentHash,transactionId,transactionBytesSha256:s.sha256,humanAuthorizationDigest,claimedAtMs:claimTime,updatedAtMs:claimTime,state:"dispatch-claimed"});
  let claimResult:unknown;try{claimResult=await store.eval(ONE_SHOT_SUBMISSION_CLAIM_LUA,[oneShotSubmissionKey(s.operationId),...fence.keys],[encodeRecord(claimed),finalValidation.validUntilMs,authorization.expiresAtMs,...fence.values]);}catch{throw new OneShotSubmissionDenied("SUBMISSION_CLAIM_OUTCOME_UNKNOWN_RELOAD_REQUIRED");}
  if(claimResult===-2)throw new OneShotSubmissionDenied("SUBMISSION_AUTHORIZATION_OR_VALIDATION_EXPIRED");if(claimResult===-3)throw new OneShotSubmissionDenied("SUBMISSION_STATE_CHANGED_BEFORE_CLAIM");if(claimResult===0){const concurrent=await readOneShotSubmissionRecord(store,s.operationId);requireSubmit(concurrent!==null,"SUBMISSION_CLAIM_OUTCOME_UNKNOWN_RELOAD_REQUIRED");assertSameSubmission(concurrent,s,transactionId);return resultFromRecord(concurrent,true);}requireSubmit(claimResult===1,"SUBMISSION_CLAIM_OUTCOME_UNKNOWN_RELOAD_REQUIRED");
  let transport:{outcome:"accepted"|"unknown";transactionId:string},reason:string|undefined;try{const raw=await dependencies.dispatchExactTestnet(Object.freeze({network:"testnet",operationId:s.operationId,transactionId,transactionBytesBase64:s.bytesBase64,transactionBytesSha256:s.sha256,humanAuthorizationDigest}));if(raw&&(raw.outcome==="accepted"||raw.outcome==="unknown")&&raw.transactionId===transactionId)transport=raw;else{transport={outcome:"unknown",transactionId};reason="TRANSPORT_RESULT_INVALID";}}catch{transport={outcome:"unknown",transactionId};reason="TRANSPORT_OUTCOME_UNKNOWN";}
  const updatedAtMs=tick(),finalRecord:OneShotSubmissionRecord=Object.freeze({...claimed,updatedAtMs,state:transport.outcome==="accepted"?"dispatch-accepted":"dispatch-unknown"});let storageFinalized=false;try{storageFinalized=await store.eval(ONE_SHOT_SUBMISSION_FINALIZE_LUA,[oneShotSubmissionKey(s.operationId)],[encodeRecord(claimed),encodeRecord(finalRecord)])===1;}catch{storageFinalized=false;}if(!storageFinalized)return Object.freeze({...resultFromRecord(claimed,false,false),reason:"SUBMISSION_FINALIZATION_UNKNOWN_RECONCILE_EXACT_TRANSACTION" as const});return Object.freeze({...resultFromRecord(finalRecord,false,true),...(reason?{reason}:{})});
}